defaults: &defaults
  adapter: mysql2
  username: root
  password: root
  host: localhost

development:
  database: mczach_dev
  <<: *defaults

test:
  database: mczach_test
  <<: *defaults
production:
  database: mczach_pro
  <<: *defaults
